### PR TITLE
12 users controller and admin account

### LINKED ISSUE #12: Users controller and admin account
Make a user controller and admin user account which is created during the first system start. First admin account should have the username set to “Admin” and password set to “Admin123!”. Login should be done through jwt token Only one admin account should be created. In the admin account set IsAdmin to true.
Passwords have to be hashed.
- Guests can register to kebab finder using username, email and password. Passwords should consist of: at least one uppercase letter, lowercase letter, at least one number and a special character. It also should consist of at least 8 characters. Username should consist of: between 3-18 letters. On success, don’t login the user, instead just return status. Newly registered accounts should have FirstLogin set to true.
- User can login using his username and password. Only user can use this route (admin can't)
- Admin can login using his username and password. Only admin can use this route (user can't)
- Route to change admin password for the first time depending on FirstLogin in user db.
- Users can edit their account. Only editing of username and password should be allowed. 
- Admin can remove any user account by id

### PR DESCRIPTION
**Pull request by W-Worach**
Added seeder with name “Admin” password “Admin123!” and email "admin@example.com"
Added 2 routes for login for admin and user
Added 2 routes to change password and username for users
Added route to change admin password after first login
Added route to delete user by id 
Added route to see all users
changed all routes so all have prefix /api/...

logging in is done by email and password

### CODE REVIEW

**Review by Wiktor-Wojciechowski — COMMENTED** [review]
Looks okay but why is there so much code commented out?

**Comment by W-Worach** [comment]
If we're talking about those in controllers, then there are annotations for generating swagger documentation

**Review by MatWisie — CHANGES_REQUESTED** [review]
Change login routes to login with username as it is described in issue, then its good to go.

**Comment by W-Worach** [comment]
> Change login routes to login with username as it is described in issue, then its good to go.

@MatWisie  
I made the required changes in this commit https://github.com/MatWisie/KebabFinder-API/pull/25/commits/36225aa18e50fff2fd77cac366c446043ef03173

**Review by MatWisie — APPROVED** [review]

**Pull request merged**
